# Generated by Django 4.1 on 2024-02-15 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserOverview",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="カード番号",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="氏名")),
                ("birthday", models.DateField(verbose_name="生年月日")),
                (
                    "gender",
                    models.IntegerField(
                        choices=[(1, "男性"), (2, "女性"), (3, "その他")],
                        default=1,
                        verbose_name="性別",
                    ),
                ),
                ("zip_code1", models.CharField(max_length=3, verbose_name="郵便番号1")),
                ("zip_code2", models.CharField(max_length=4, verbose_name="郵便番号2")),
                ("address", models.CharField(max_length=200, verbose_name="住所")),
                ("phone_number", models.CharField(max_length=20, verbose_name="電話番号")),
                (
                    "temperature",
                    models.DecimalField(
                        decimal_places=1, max_digits=3, verbose_name="体温"
                    ),
                ),
                (
                    "created_date",
                    models.DateField(auto_now_add=True, verbose_name="登録日"),
                ),
            ],
            options={
                "verbose_name_plural": "利用者概要",
            },
        ),
        migrations.CreateModel(
            name="UsageRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("use_date", models.DateField(auto_now_add=True, verbose_name="利用日")),
                (
                    "use_session",
                    models.IntegerField(
                        choices=[(1, "午前の部"), (2, "午後の部"), (3, "夜の部")],
                        default=1,
                        verbose_name="利用時間帯",
                    ),
                ),
                (
                    "useroverview_fk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.useroverview",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "利用記録",
            },
        ),
    ]
